language: node_js

node_js:
  - 'stable'

cache:
  yarn: true
  directories:
    - $HOME/.npm

install:
  - sudo pip install awscli
  - yarn install

script:
  - yarn lint
  - yarn test:coverage
  - yarn build
  - aws s3 sync ./build s3://$S3_BUCKET_NAME
