name: CI

on: [push]

jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn install
