name: CI

on: [push]

jobs:
  terraform:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: terraform-fmt
        uses: hashicorp/terraform-github-actions/fmt@v0.44
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: ./infrastructure

  node:
    name: Lint, test, deploy
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: yarn install
      - name: Run linters
        run: yarn lint
      - name: Run tests
        run: yarn test:coverage
      - name: Build & deploy
        if: github.ref == 'refs/heads/master'
        env:
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          yarn build
          aws s3 sync ./build s3://$AWS_S3_BUCKET_NAME
          aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
